### PR TITLE
Restore original John Papa IIFE recommendation

### PR DESCRIPTION
**Pull request by markschabacker**
I think that IIFE’s are a useful defensive coding practice.  They’re probably not necessary in a well-written and clean application but provide a safety net in an application in any other state.

Here’s my really quick list of pros and cons for IIFEs:
#### Pro
- Encapsulated scope ensures insulation from inadvertent global collisions
- I’d argue that they are idiomatic JavaScript at this point
#### Con
- 2 extra lines of code: `(function(){` and `})();`
- Extra level of indentation
- Can be confusing to inexperienced JS devs

I haven’t used Grunt or Gulp in a production app and JSLint will probably catch most of the issues that IIFE’s prevent.  Perhaps an automated toolchain can remove the need for IIFE’s on a project dedicated to clean code but that’s not what I typically see in the wild.

### CODE REVIEW

**Comment by mbcooper** [comment]
Agreed it is a good safety mechanism and we should add it back. 

My suggested approach is from a  Todd Motto blog .. Have it added using a gulp/grunt task during non-local builds.  I've trying it out on a personal project now. I am using gulp wrap.

**Comment by mbcooper** [comment]
Here is [Todd's article](http://toddmotto.com/minimal-angular-module-syntax-approach-using-an-iife/)

"If you're globally wrapping your code with an IIFE automatically with something like Grunt/Gulp, then extra points for you."

I just don't like the idea of writing plumbing that could be automated.

**Comment by johnrhampton** [comment]
My current opinion is to keep IIFE out of individual angular modules and add it via Gulp or Grunt.  I am using the same library Coop mentions above (gulp-wrap) to wrap my output in an IIFE.  I like this approach b/c it gives our app the IIFE safety, but does not muddy up our modules.  

In my opinion, adding an IIFE seems to be more of a necessity when writing apps that could be potential dependencies for other applications, but it is good practice.  Similar to how adding {} around one line conditional statements is not required, but good practice.

My suggestion for this section is to mention gulp-wrap and add an example showing how easily we can accomplish this.  Something like the below in our task that concats, annotates, and uglifies our js.

<code>  
        .pipe($.wrap('(function(){\n"use strict";\n<%= contents %>\n})();'))
</code>

**Comment by mbcooper** [comment]
We are in sync.  I updated as such

**Pull request merged**
